# Definition of existing GKE cluster
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: e-commerce-ms
  type: core.Directory
  children:
  - name: gcp-gke-gke-marcdev-e-commerce-devops-europe-west-1-ecommerce-cluster-1
    type: k8s.Master
    username: gke_marcdev-e-commerce-devops_europe-west1_ecommerce-cluster-1
    password: !value K8SMasterPassword
    apiServerURL: https://35.187.88.71
    skipTLS: true
    children:
    - name: xl-demo
      type: k8s.Namespace
      namespaceName: xl-demo
---
# Definition of existing GKE Environment
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: e-commerce-ms
  type: core.Directory
  children:
  - name: gcp-gke-e-commerce-ms
    type: udm.Environment
    members:
    - Infrastructure/e-commerce-ms/gcp-gke-gke-marcdev-e-commerce-devops-europe-west-1-ecommerce-cluster-1/xl-demo
    - Infrastructure/e-commerce-ms/gcp-gke-gke-marcdev-e-commerce-devops-europe-west-1-ecommerce-cluster-1