apiVersion: xl-release/v1
kind: Templates
spec:
- name: e-commerce-ms
  type: xlrelease.Folder
  children:
  - name: e-commerce-ms-destroy
    type: xlrelease.Release
    description: |
      This XL Release template shows how to undeploy an application, based on microservices architecture, to GCP GKE using XL Deploy and Terraform.
    tags:
    - GCP
    - GKE
    - e-commerce-ms
    scriptUsername: !value XL_RELEASE_USERNAME
    scriptUserPassword: !value XL_RELEASE_PASSWORD
    phases:
    - name: Undeploy Application
      type: xlrelease.Phase
      tasks:
      - name: Undeploy stateless services
        type: xlrelease.ParallelGroup
        tasks:
        - name: Undeploy registry svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/e-commerce-ms/gcp-gke-gke-marcdev-e-commerce-devops-europe-west-1-ecommerce-cluster-1/e-commerce-ms-registry
        - name: Undeploy invoice svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/e-commerce-ms/gcp-gke-gke-marcdev-e-commerce-devops-europe-west-1-ecommerce-cluster-1/e-commerce-ms-invoice
        - name: Undeploy notification svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/e-commerce-ms/gcp-gke-gke-marcdev-e-commerce-devops-europe-west-1-ecommerce-cluster-1/e-commerce-ms-notification
        - name: Undeploy store svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/e-commerce-ms/gcp-gke-gke-marcdev-e-commerce-devops-europe-west-1-ecommerce-cluster-1/e-commerce-ms-store
      - name: Undeploy stateful services
        type: xlrelease.ParallelGroup
        tasks:
        - name: Undeploy invoice mysql svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/e-commerce-ms/gcp-gke-gke-marcdev-e-commerce-devops-europe-west-1-ecommerce-cluster-1/e-commerce-ms-invoice-mysql
        - name: Undeploy store mysql svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/e-commerce-ms/gcp-gke-gke-marcdev-e-commerce-devops-europe-west-1-ecommerce-cluster-1/e-commerce-ms-store-mysql
        - name: Undeploy notification mongodb svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/e-commerce-ms/gcp-gke-gke-marcdev-e-commerce-devops-europe-west-1-ecommerce-cluster-1/e-commerce-ms-notification-mongodb